### ISSUE TITLE
Is type of the parameter of `encode` string?

### ISSUE THREAD

**Issue by wontheone1** [mathiasbynens/windows-1252#4]
const decoded = windows1252.decode(data);
    console.log(decoded); 

// this output broken string like ������ ����� ���� ���� ���� AA�� A�� ���","���� : ������, ��� 

    console.log(typeof decoded); // string
    const encoded = windows1252.encode(decoded);

 // This throws `readFileAfterClose` error. This is weird because I gave string as parameter but why did it try to read a file? see screenshot

![Screenshot 2020-06-08 at 9 00 49](https://user-images.githubusercontent.com/11784756/83997279-b6643400-a966-11ea-8f85-ec3d213e8e2a.png)

**Comment by wontheone1** [comment]
I have one question, please. 

I have a string that is encoded as ISO-8859 for some Korean text, I can treat it as `windows-1252` right?

**Comment by mathiasbynens** [comment]
I have no idea what's going on in your screenshot. Please share a minimal repro. I'll close this for now.
