### ISSUE TITLE
Is this no longer maintained?

### ISSUE THREAD

**Issue by raijinsetsu** [mathiasbynens/windows-1252#5]
There are several issues that have been open for years and no development has been done here in a long time.

I have an issue myself, but it does not seem worthwhile to try to get this library to work correctly if the maintainer(s) are no longer taking PRs.

If this project is no longer maintained, could you please update the README and NPM package so that we developers do not attempt to use it?

**Comment by ffMathy** [comment]
I guess not.

**Comment by ffMathy** [comment]
@mathiasbynens I suppose that means yes then? Care to elaborate?
