### ISSUE TITLE
TypeScript typings?

### ISSUE THREAD

**Issue by ffMathy** [mathiasbynens/windows-1252#6]
Can we get TypeScript typings for this library?

**Comment by Treverix** [comment]
This works for me:

```typescript
declare module 'windows-1252' {

  type EncodeOptions = {
    mode: 'fatal' | 'html'
  }
  type DecodeOptions = {
    mode: 'fatal' | 'replacement'
  }

  type Win1252 = {
    version: string;
    labels: string[];
    encode: (text: string, options?: EncodeOptions) => string;
    decode: (text: string, options?: DecodeOptions) => string;
  }

  declare const windows1252: Win1252
  export default windows1252;
}
```

I stored it as some `d.ts` file (for example `./types/windows1252.d.ts` - the name doesn't matter) and then I was able to import like this:

`import windows1252 from 'windows-1252';`

Hope it helps :)

**Comment by ffMathy** [comment]
Awesome. Would be great to submit this into this package, to make it inbuilt.

**Comment by mathiasbynens** [comment]
Patches welcome! Note that @Treverix's version might need some minor changes now that the library is a proper JavaScript module, and no longer exports the `version` property.

**Comment by floratmin** [comment]
This works for me:
```ts
declare module 'windows-1252' {

  type EncodeOptions = {
    mode: 'fatal' | 'replacement'
  }
  type DecodeOptions = {
    mode: 'fatal' | 'replacement'
  }

  export declare function encode(text: string, options?: EncodeOptions): Uint16Array;
  export declare function decode(buffer: Uint16Array | Uint8Array | Buffer | string, options?: DecodeOptions): string;
  export type labels = string[];

}
```

**Comment by mathiasbynens** [comment]
Thanks everyone. Giving this a go in a3710c0760e0b74173e4ce7fbf08c8af164e2a57. Let me know if this works for you.

**Comment by ffMathy** [comment]
Awesome stuff! Thanks.
