### ISSUE TITLE
Impossible to actually set encoding mode to anything other than error

### ISSUE THREAD

**Issue by jpd236** [mathiasbynens/windows-1252#8]
The documentation for `encode` says:

> The optional options object and its mode property can be used to set the error mode. The two available error modes are 'fatal' (the default) or 'replacement'. (Note: This differs from the spec, which recognizes 'fatal' and html modes for encoders. The reason behind this difference is that the spec algorithm is aimed at producing HTML, whereas this library encodes into an environment-agnostic Uint16Array of bytes.)

But the actual implementation [here](https://github.com/mathiasbynens/windows-1252/blob/main/src/windows-1252.src.mjs#L78) clobbers the 'replacement' mode as it only supports 'fatal' or 'html. Then, the `encodingError` method looks for 'replacement', not 'html', which means it can never actually enter the 'replacement' codepath.

To match the documentation, the reference to 'html' in `encode` should be replaced with `replacement`, I believe.

**Comment by mathiasbynens** [comment]
Thanks for the report! This should be fixed in v3.0.2. Please give it a try :)
